
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace e_Tracking
{

using System;
    using System.Collections.Generic;
    
public partial class Comment
{

    public int Id { get; set; }

    public string Text { get; set; }

    public Nullable<int> ParentId { get; set; }

    public string PrNumber { get; set; }

    public string UserId { get; set; }

    public System.DateTime UpdateDate { get; set; }

}

}
