
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace e_Tracking
{

using System;
    using System.Collections.Generic;
    
public partial class tbfollowing
{

    public long id { get; set; }

    public string userid { get; set; }

    public string flag_follow { get; set; }

    public Nullable<System.DateTime> lastmodifieddate { get; set; }

    public string lastmodifieBy { get; set; }

    public string pr_number { get; set; }

}

}
